package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-macosx-x86_64/jdk8u5/2488/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, March 18, 2014 12:37:22 AM PDT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
     * The CDR Encapsulation encoding.
     * @see CodecFactory
     */
  public static final short value = (short)(0);
}
